language: rust
sudo: false
script:
- cargo test
- cargo doc --no-deps

env:
  global:
    secure: btdSFScOk10KxYrlwXWcJVeUxVlWXV5YEsNvRWk1T+ysobKu/5uMznwB8zgxi7YtR+ICljXfJ+DhtalCYntFvGbhQ6HrKYoe7lCh0TH1GZX5sqvIdXbmoVZbeHsRV/uRshk1BBkY85cFm3afTHuh5pgGPwV+PVEcwYRrSn2JTQs=

deploy:
  provider: s3
  access_key_id: AKIAIGFX36YKEFRZJAXA
  secret_access_key:
    secure: blFcl9EMlWIiI+x8LZFWpyIxRZRScKWaftSXluFB0HLgbA1oYYX4lo8GgVYGQZ4kP3iIuL+WAlGvf3iCrAULGy0UOxLgvwOxX8XsgfCZpzF/Bw1G6od+IkPzbpNIgMtkceDhzZEmO+yatbAYCdMF0qq485QJ502inB7aeu1G94w=
  bucket: rustdoc
  local-dir: /home/travis/build/carllerche/mio/target/doc
  upload-dir: mio/master
  acl: public_read
  on:
    repo: carllerche/mio
    branch: deploy-docs
