[package]

name          = "mio"
version       = "0.4.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://carllerche.github.io/mio/mio"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
log = "0.3.1"
libc = "0.1.7"
bytes = "0.2.7"
clock_ticks = "0.0.5"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust"

[dependencies.winapi]
git = "https://github.com/retep998/winapi-rs"

[dev-dependencies]
env_logger = "0.3.0"
tempdir    = "0.3.4"

[[test]]

name = "test"
path = "test/test.rs"
